name: backend-ci.yml
on:
  pull_request:
    branches: ["develop"]
    paths:
      - "/**"

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    services:
      mysql:
        image: mysql:8.0.41
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        run: |
          echo "gradle wrapper에 권한 부여"
          chmod +x ./gradlew
        working-directory: ./

      - name: Run tests
        run: ./gradlew clean test --stacktrace
        working-directory: ./src
